#!/usr/bin/env python3
"""
Tier 8, Item 3 - Interleaved randomized mitigation comparison instead of consecutive blocks.
================================================================================================
Question addressed by this experiment
----------------------
sigconf.tex (Section 5.5/`sec:mitigationresults`) reports that timeout scaling
increased completion at 75% configured loss from 14/20 to 20/20. However, the
Tier5 arms (none/adaptive_timeout/context_cache) ran as consecutive blocks rather
than interleaved trials. This confounds condition with run period, including host
load, thermal state, and model-server state. This experiment runs the same 660
trials (11 loss levels x 4 tasks x 5 repeats x 3 conditions) while randomizing the
condition order. If the 14/20 versus 20/20 difference remains, the result is stronger
than a hypothesis generated by block timing.

Design
----------
Create all 660 trial specifications (condition x loss_pct x task x repeat), shuffle
them with the fixed seed below, and save the order to
`<log-dir-prefix>_execution_order.json` before execution. This allows later checks
for associations between execution time and condition. Logs remain separated by
condition so existing parsers continue to work.
(`logs_..._none/`, `logs_..._adaptive_timeout/`, `logs_..._context_cache/`) so
the existing parsers and analysis scripts can continue without changes.

Checkpoint/resume uses the same trial key as Tier5 (condition+scenario+task+repeat),
so interrupted interleaved runs can resume from the correct point.

Scope
-------
11 loss levels (0,1,5,10,15,20,25,30,40,50,75%) x 4 tasks x 5 repeats x 3
conditions = 660 total trials, exactly matching Tier5 (n=20 per condition per loss level).

Usage
---------
    python3 Tier8_EnsureScopeClosure/run_tier8_randomized_mitigation.py --dry-run
    python3 Tier8_EnsureScopeClosure/run_tier8_randomized_mitigation.py --resume
"""
import argparse
import json
import os
import random
import sys
import time

_THIS_DIR = os.path.dirname(os.path.abspath(__file__))
_PROJECT_ROOT = os.path.dirname(_THIS_DIR)
sys.path.insert(0, _PROJECT_ROOT)
sys.path.insert(0, _THIS_DIR)  # Insert after _PROJECT_ROOT so this directory has priority.

from controller import NetworkController  # noqa: E402
from logger import ExperimentLogger  # noqa: E402
from checkpoint_utils import (  # noqa: E402
    load_checkpoint, save_checkpoint, mark_completed, should_skip,
)
from experiment.scenarios import PACKET_LOSS_LEVELS_PCT  # noqa: E402
from experiment.tasks import TASKS  # noqa: E402

CONDITIONS = ["none", "adaptive_timeout", "context_cache"]
REPEATS = 5

# Keep the seed fixed and explicit rather than using time/os.urandom so the order
# can be reproduced for auditing. Change it only when a new order is intended,
# and record the actual seed in the report.
RANDOM_SEED = 20260101


def _loss_scenarios():
    scenarios = []
    for loss_pct in PACKET_LOSS_LEVELS_PCT:
        scenarios.append({
            "name": f"tier8_loss_loss{str(loss_pct).replace('.', 'p')}",
            "delay_ms": 0,
            "requested_delay_ms": 0,
            "jitter_ms": 0,
            "loss_pct": loss_pct,
            "bandwidth_kbit": None,
            "note": "",
        })
    return scenarios


def _trial_key(condition, scenario, task_name, repeat_index):
    return f"{condition}__{scenario['name']}__{task_name}__run{repeat_index}"


def build_shuffled_trial_list(seed: int):
    """Create all 660 trial specifications, shuffle them, and return a list of dicts:
    {"condition", "scenario", "task_name", "task_prompt", "repeat_index"}"""
    scenarios = _loss_scenarios()
    tasks = TASKS

    trials = []
    for repeat_index in range(1, REPEATS + 1):
        for scenario in scenarios:
            for task_name, task_prompt in tasks.items():
                for condition in CONDITIONS:
                    trials.append({
                        "condition": condition,
                        "scenario": dict(scenario),
                        "task_name": task_name,
                        "task_prompt": task_prompt,
                        "repeat_index": repeat_index,
                    })

    rng = random.Random(seed)
    rng.shuffle(trials)
    return trials


def run_single_trial(net, scenario, task_name, task_prompt, run_index, log_dir,
                     condition, multi_agent_module, sequence_index):
    print(f"  [seq={sequence_index}] [{scenario['name']}] cond={condition} task={task_name} "
          f"run={run_index} -> loss={scenario['loss_pct']}%")

    logger = ExperimentLogger(scenario=scenario, task_name=task_name,
                              run_index=run_index, log_dir=log_dir)
    logger.data["execution_sequence_index"] = sequence_index

    apply_result = net.apply(
        delay_ms=scenario["delay_ms"],
        jitter_ms=scenario["jitter_ms"],
        loss_pct=scenario["loss_pct"],
        bandwidth_kbit=scenario.get("bandwidth_kbit"),
    )
    logger.data.setdefault("network_commands", []).append({"action": "apply", "result": apply_result})

    if apply_result.get("returncode") not in (0, None):
        logger.log_error(error_type="invalid_trial", detail="network apply failed; skipped LLM run")
        logger.log_outcome(success=False, rounds=0, rejections=0,
                           elapsed_seconds=time.time() - logger.start_time)
        print("    -> INVALID TRIAL: network apply failed")
    else:
        try:
            result = multi_agent_module.run_multi_agent_task(
                task_prompt, logger=logger, task_name=task_name,
                mitigation=condition, network_condition=scenario,
            )
            print(f"    -> success={result['success']} rounds={result['rounds']} "
                  f"elapsed={result['elapsed_seconds']}s")
        except Exception as exc:  # noqa: BLE001
            logger.log_error(error_type="fatal_error", detail=str(exc)[:300])
            logger.log_outcome(success=False, rounds=0, rejections=0,
                               elapsed_seconds=time.time() - logger.start_time)
            print(f"    -> FATAL ERROR: {exc}")

    clear_result = net.clear()
    logger.data.setdefault("network_commands", []).append({"action": "clear", "result": clear_result})
    return logger.save()


def main():
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--iface", default="eth0")
    ap.add_argument("--log-dir-prefix",
                    default=os.path.join(_THIS_DIR, "logs_tier8_randomized_mitigation"))
    ap.add_argument("--seed", type=int, default=RANDOM_SEED,
                    help="Random seed for trial ordering (fixed by default for reproducibility).")
    ap.add_argument("--dry-run", action="store_true")
    ap.add_argument("--resume", action="store_true")
    args = ap.parse_args()

    trials = build_shuffled_trial_list(args.seed)
    total = len(trials)
    per_condition = total // len(CONDITIONS)

    print("Tier 8, Item 3 - interleaved randomized mitigation comparison")
    print(f"  seed = {args.seed}")
    print(f"  {len(PACKET_LOSS_LEVELS_PCT)} loss levels x {len(TASKS)} tasks x {REPEATS} repeats "
          f"x {len(CONDITIONS)} conditions = {total} total trials ({per_condition}/condition)")
    for c in CONDITIONS:
        print(f"    - {c}: log -> {args.log_dir_prefix}_{c}/")

    order_manifest_path = f"{args.log_dir_prefix}_execution_order.json"
    manifest = [
        {
            "sequence_index": i,
            "condition": t["condition"],
            "scenario_name": t["scenario"]["name"],
            "loss_pct": t["scenario"]["loss_pct"],
            "task_name": t["task_name"],
            "repeat_index": t["repeat_index"],
        }
        for i, t in enumerate(trials)
    ]
    os.makedirs(os.path.dirname(order_manifest_path) or ".", exist_ok=True)
    with open(order_manifest_path, "w", encoding="utf-8") as fh:
        json.dump({"seed": args.seed, "total_trials": total, "order": manifest}, fh,
                  ensure_ascii=False, indent=2)
    print(f"  Execution order saved to: {order_manifest_path}")
    print(f"  Estimated time: ~{total * 60 / 3600:.1f} hours (roughly 60s/trial)")

    if args.dry_run:
        print("\nDRY RUN: no network impairment, LLM call, or trial log will be created "
              "(the execution_order.json manifest is a planning artifact and has "
              "no effect on the network or LLM)")
        return

    import multi_agent as multi_agent_module  # noqa: E402

    net = NetworkController(iface=args.iface, direction="egress")

    checkpoints = {c: (load_checkpoint(f"{args.log_dir_prefix}_{c}") if args.resume else None)
                   for c in CONDITIONS}

    start = time.time()
    for i, t in enumerate(trials):
        condition = t["condition"]
        log_dir = f"{args.log_dir_prefix}_{condition}"
        key = _trial_key(condition, t["scenario"], t["task_name"], t["repeat_index"])
        checkpoint = checkpoints[condition]
        if should_skip(args.resume, checkpoint, key):
            print(f"  [SKIP seq={i}] {key}")
            continue
        log_file = run_single_trial(net, t["scenario"], t["task_name"], t["task_prompt"],
                                    t["repeat_index"], log_dir, condition, multi_agent_module, i)
        if checkpoint is not None:
            mark_completed(log_dir, checkpoint, key, log_file)

        print(f"\nCompleted in {(time.time() - start) / 60:.1f} minutes")
        print("Next step: parse the three log folders and compare completion at 75% loss "
            "before and after removing run-block confounding from the Tier5 result.")


if __name__ == "__main__":
    main()
